platform :ios, ‘9.0’
use_frameworks!
inhibit_all_warnings!

target 'Fii' do
    # 网络
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'Starscream'
    # JSON
    pod 'SwiftyJSON'
    # Reactive
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxDataSources'
    # UI
    pod 'SnapKit'
    pod 'MJRefresh'
    pod 'Charts'
    # Grama
    pod 'Then', '~> 2.4.0'
    # SDK
    pod 'RongCloudIM/IMLib'
    pod 'RongCloudIM/IMKit'
end
