
package com.foxconn.loginClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* LoginImplService service = new LoginImplService();
* LoginImpl portType = service.getLoginImplPort();
* portType.register(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "LoginImplService", targetNamespace = "http://fun.foxcoon.com/", wsdlLocation = "http://localhost:9003/loginService/login?wsdl")
public class LoginImplService extends Service {

	private final static URL LOGINIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.foxconn.loginClient.LoginImplService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.foxconn.loginClient.LoginImplService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:9003/loginService/login?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://localhost:9003/loginService/login?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		LOGINIMPLSERVICE_WSDL_LOCATION = url;
	}

	public LoginImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public LoginImplService() {
		super(LOGINIMPLSERVICE_WSDL_LOCATION, new QName("http://fun.foxcoon.com/", "LoginImplService"));
	}

	/**
	 * 
	 * @return returns LoginImpl
	 */
	@WebEndpoint(name = "LoginImplPort")
	public LoginImpl getLoginImplPort() {
		return super.getPort(new QName("http://fun.foxcoon.com/", "LoginImplPort"), LoginImpl.class);
	}

}
