
package com.foxconn.loginClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "LoginImpl", targetNamespace = "http://fun.foxcoon.com/")
public interface LoginImpl {

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "register", targetNamespace = "http://fun.foxcoon.com/", className = "com.foxcoon.loginClient.Register")
	@ResponseWrapper(localName = "registerResponse", targetNamespace = "http://fun.foxcoon.com/", className = "com.foxcoon.loginClient.RegisterResponse")
	public String register(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "checkLogin", targetNamespace = "http://fun.foxcoon.com/", className = "com.foxcoon.loginClient.CheckLogin")
	@ResponseWrapper(localName = "checkLoginResponse", targetNamespace = "http://fun.foxcoon.com/", className = "com.foxcoon.loginClient.CheckLoginResponse")
	public String checkLogin(@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

}
