
package com.foxconn.replyClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Reply", targetNamespace = "http://inter.foxcoon.com/")
public interface Reply {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "getReply", targetNamespace = "http://inter.foxcoon.com/", className = "com.foxcoon.replyClient.GetReply")
	@ResponseWrapper(localName = "getReplyResponse", targetNamespace = "http://inter.foxcoon.com/", className = "com.foxcoon.replyClient.GetReplyResponse")
	public String getReply(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
