
package com.foxconn.replyClient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
* ReplyImplService service = new ReplyImplService();
* Reply portType = service.getReplyImplPort();
* portType.getReply(...);
 * </pre>
 * </p>
 * 
 */
@WebServiceClient(name = "ReplyImplService", targetNamespace = "http://fun.foxcoon.com/", wsdlLocation = "http://localhost:9003/talkService/getReply?wsdl")
public class ReplyImplService extends Service {

	private final static URL REPLYIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(com.foxconn.replyClient.ReplyImplService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.foxconn.replyClient.ReplyImplService.class.getResource(".");
			url = new URL(baseUrl, "http://localhost:9003/talkService/getReply?wsdl");
		} catch (MalformedURLException e) {
			logger.warning(
					"Failed to create URL for the wsdl Location: 'http://localhost:9003/talkService/getReply?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		REPLYIMPLSERVICE_WSDL_LOCATION = url;
	}

	public ReplyImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ReplyImplService() {
		super(REPLYIMPLSERVICE_WSDL_LOCATION, new QName("http://fun.foxcoon.com/", "ReplyImplService"));
	}

	/**
	 * 
	 * @return returns Reply
	 */
	@WebEndpoint(name = "ReplyImplPort")
	public Reply getReplyImplPort() {
		return super.getPort(new QName("http://fun.foxcoon.com/", "ReplyImplPort"), Reply.class);
	}

}
